version: '3.9'

services:
  api:
    container_name: pulseboard-api
    image: pulseboard-api
    environment:
      - NODE_ENV=production
      - PORT=8080
      - API_VERSION=1
    build: .
    ports:
      - '8080:8080'
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16-alpine
    container_name: pulseboard-db
    environment:
      POSTGRES_USER: pulseboard
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pulseboard
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: pulseboard-redis
    ports:
      - '6379:6379'
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
