version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: pulseboard-db
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-pulseboard}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-pulseboard}
    ports:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pulseboard-net
    restart: unless-stopped

  app:
    build: .
    container_name: pulseboard-app
    env_file:
      - .env
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: ${PORT:-8080}
      DATABASE_URL: postgres://${POSTGRES_USER:-pulseboard}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-pulseboard}
    ports:
      - '8080:8080'
    depends_on:
      - db
    networks:
      - pulseboard-net
    restart: unless-stopped
    command: ['sh', '-c', 'pnpm exec prisma db push && pnpm start']

volumes:
  postgres_data:

networks:
  pulseboard-net:
    driver: bridge
